name: budgets
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  google_fonts: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^8.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
